debug-api-enable: true
data-dir: /home/anatol/.bee/staging
verbosity: trace
network-id: 2
bootnode: /dnsaddr/bootnode.staging.ethswarm.org
swap-endpoint: https://rpc.slock.it/goerli
api-addr: :1633
bootnode-mode: false
clef-signer-enable: false
clef-signer-endpoint: http://localhost:8550
clef-signer-ethereum-address: ""
cors-allowed-origins: []
db-capacity: "5000000"
debug-api-addr: :1635
gateway-mode: false
global-pinning-enable: false
help: false
nat-addr: ""
p2p-addr: :1634
p2p-quic-enable: false
p2p-ws-enable: false
password: "password"
password-file: ""
payment-early: "1000000000000"
payment-threshold: "10000000000000"
payment-tolerance: "50000000000000"
resolver-options: []
standalone: false
swap-enable: true
swap-factory-address: ""
swap-initial-deposit: "100000000000000000"
tracing-enable: false
tracing-endpoint: 127.0.0.1:6831
tracing-service-name: bee
welcome-message: ""
full-node: false